bugsnag-elixir/bugsnag-elixir

- lib/bugsnag/payload.ex
- test/bugsnag_test.exs
Added parentheses to pipe to resolve ambiguity warning and fixed the `no clause will ever match` warning in `bugsnag_test.exs`
> resolved compiler warnings

- lib/bugsnag/payload.ex
- test/bugsnag/payload_test.exs
add `metaData` to the payload to send arbitrary data to bugsnag per the open issue.
> Add metadata to payload

- README.md
- mix.exs
Bugsnag needs to start httpoison before using it. Otherwise when running in prod no reporting will silently fail.
I also updated the readme for best practise for starting applications.
> Autostart httpoison when starting bugsnag application

- config/config.exs
- lib/bugsnag.ex
- lib/bugsnag/logger.ex
- lib/bugsnag/payload.ex
- mix.exs
- test/bugsnag/logger_test.exs
- test/support/error_server.exs
- test/test_helper.exs
Props to Honeybadger, as this work was heavily based on their Logger. Basically it sends error reports from OTP/tasks/processes/etc. So you don't need to manually wrap every expression within try/rescue block.
> Feature: Add error logger.

- README.md
- lib/bugsnag/payload.ex
this replaces runtime calls to `Mix.env` with an application configuration `release_stage` as mix might not be available in exrm releases.
> remove runtime call to Mix.env

- README.md
- lib/bugsnag/payload.ex
- test/bugsnag/payload_test.exs
~~Since #29 adds documentation for the options, this kinda depends on that PR... and we might wanna merge #29 first and update this afterwards.~~
(did that)
> Adds ability to override the configured api_key via option

- README.md
- lib/bugsnag.ex
- mix.exs
- test/bugsnag_test.exs
As mentioned briefly in an (admittely only barely related issue) I added support for calling the `Bugsnag.report/2` API synchronously via `Bugsnag.sync_report/2`.
This doesn't  break backwards compatibility.
Thoughts, @mootpointer ?
> Adds support for synchronous reports via `Bugsnag.sync_report/2`

- README.md
- lib/bugsnag.ex
- mix.exs
Adds `mod: {Bugsnag, []}` to the application definition in mix.exs,
which means that Mix can start the app correctly, and automatically pick
up uncaught exceptions when `use_logger: true` is set.
I think this makes this more intuitive to use - just set the config in `config/config.exs`, add it to your `applications` list in `mix.exs` and off you go.
> Enable app to be started automatically by Mix

- mix.exs
Based on the discussion in #25 I used `or` so that backwards compatibility won't be removed. Assuming the tests are comprehensive, the change doesn't break anything in the library. Thanks!
> use latest version of poison

- .travis.yml
- mix.exs
This seemed like it could use a cleanup, especially since the Elixir and OTP versions we're testing have had several patch releases since the last update to this file.
Regarding version support: I'm taking a cue from Phoenix here, which currently supports Elixir 1.3+. This still gives us coverage for 3 previous releases of Elixir, and allows us to drop OTP 18.
> Update build matrix: remove Elixir 1.2, add 1.5 and 1.6

- config/config.exs
- lib/bugsnag.ex
- test/bugsnag_test.exs
- test/test_helper.exs
An updated take on #34. Rather than crashing only once we try to report an error, the app will fail to start entirely if no `api_key` is present and we are in a "notifying" release stage.
Like the original, this is backwards-incompatible, in that misconfigured apps that used to "work" will now crash. Not sure if this warrants a major-version bump. @coburncoburn, thoughts?
> Warn when API key is not configured

- README.md
Someone reading the previous version might be tempted to call their production release stage `prod`. This might lead to no production errors being logged when relying on the default of `notify_release_stages`.
I've tried to make the default more clear, and changed the example `release_stage` to use the same name as the default.
> Make the default of notify_release_stages explicit

- README.md
- lib/bugsnag.ex
- lib/bugsnag/payload.ex
- test/bugsnag/payload_test.exs
This should allow setting the `hostname` in a config which will then report it to the Device tab and the Summaries sidebar in Bugsnag.
```
config :bugsnag,
client: Bugnsnag,
api_key: System.get_env("BUGSNAG_API_KEY"),
hostname: System.get_env("HOSTNAME"),
...
```
In this case the application is released in a container. Currently the Bugsnags are not reported with a device tab even if the the `hostname` is set in the config. Using the `fetch_option` function it will default to using the the application environment set to `[:bugsnag][:hostname]` if it is not in the `options` map.
> Add hostname config option

- lib/bugsnag/logger.ex
Minimal Fix for Issue #59 
The [Erlang `error_logger` interface's `add_report_handler`](https://github.com/jarednorman/bugsnag-elixir/blob/b477ef05049ed3370f08e4fb1515490d97f0a160/lib/bugsnag.ex#L17) function [requires a `gen_event` interface](http://erlang.org/doc/man/error_logger.html#add_report_handler-1). [Elixir has deprecated `GenEvent`, and for use cases as these recommends using the `gen_event` behaviour](https://hexdocs.pm/elixir/GenEvent.html#content). This change does that.
Confirmed that tests passed.
> Replace GenEvent with gen_event

- .formatter.exs
- .travis.yml
- config/config.exs
- lib/bugsnag.ex
- lib/bugsnag/logger.ex
- lib/bugsnag/payload.ex
- mix.exs
- test/bugsnag/logger_test.exs
- test/bugsnag/payload_test.exs
- test/bugsnag_test.exs
- test/test_helper.exs
With apologies for the one-time commit noise... this will cause CI to fail if any code is not formatted, so the `mix format` style will be enforced from here on.
> Add `mix format` to CI and format the code

- README.md
- lib/bugsnag.ex
- lib/bugsnag/payload.ex
- test/bugsnag/payload_test.exs
Since #74 has not seen activity in some weeks, I built on the great initial implementation by @shantiii and added some tests. Looking forward to fixing the "everything is in-project" issue since the faulty grouping has been bugging us (pun intended?).
> Enable marking stack frames as "in-project"

- README.md
- lib/bugsnag.ex
- test/bugsnag_test.exs
After upgrading to phoenix 1.4 bugsnag was filled with 404 because they are reported to logger as errors. This change adds a hook that will allow end users to filter whatever logs they don't want to be reported.
> Configurable log message filter

- lib/bugsnag/payload.ex
- test/bugsnag/payload_test.exs
In some case people might use atoms in the severity option.
> Add support for atoms in severity option

- README.md
- lib/bugsnag.ex
- lib/bugsnag/payload.ex
- mix.exs
- test/bugsnag/payload_test.exs
- test/bugsnag_test.exs
1. #84 introduced a bug. Since Jason cannot encode arbitrary structs, a custom `Jason.Encoder` implementation is required. If a `Jason.Encoder` implementation is [derived](https://github.com/jarednorman/bugsnag-elixir/blob/ebf3569ada87e27f83bc21935fb96f4aab82b23d/lib/bugsnag/payload.ex#L10), only known struct fields are going to be encoded (i.e. `api_key`, `notifier`, `events`). The `Payload.new/3` [constructor](https://github.com/jarednorman/bugsnag-elixir/blob/ebf3569ada87e27f83bc21935fb96f4aab82b23d/lib/bugsnag/payload.ex#L17-L21) puts the `apiKey` field (which is used by the Bugsnag endpoint) into the struct and leaves `api_key` nil. Because of the derived implementation of `Jason.Encoder`, the `apiKey` is always ignored when the payload is encoded to JSON; it produces JSON objects …
> Fix Jason producing encoded JSON payloads without the `apiKey` field; make JSON library configurable

- lib/bugsnag.ex
Remove warning on Elixir 1.10  by moving restart option to start_child as recommended:
https://hexdocs.pm/elixir/Task.Supervisor.html#start_link/1
> Remove warning on Elixir 1.10 

- lib/bugsnag.ex
- lib/bugsnag/reporter.ex
> Code re-organization

- test/bugsnag_test.exs
This PR fixes the issue of tests failing intermittently (reported in https://github.com/bugsnag-elixir/bugsnag-elixir/issues/104).
It turns out a test in `BugsnagTest` was causing a task to be started by the reporter, under `Bugsnag.TaskSupervisor`, but it wasn't waiting for the task to finish or checking anything in it.
This was cauing tests in `Bugsnag.LoggerTest` to fail when the problematic test was executed before them. The dangling task was getting executed while the logger tests were running, causing `HTTPMock` to be called twice which crashes the Mox process and every other test that depend on it.
This PR adds a snippet that is executed after each test in `BugsnagTest` to terminate possible dangling tasks in the supervisor and so prevent this issue from occurring again.
> Ensure tasks under Bugsnag.TaskSupervisor don't spill into other tests

- README.md
- lib/bugsnag/payload.ex
- test/bugsnag/payload_test.exs
This PR addresses https://github.com/bugsnag-elixir/bugsnag-elixir/issues/97 by introducing a new option, `error_class`, which can be passed to [`Bugsnag.Reporter.report/2`](https://github.com/bugsnag-elixir/bugsnag-elixir/blob/577107f1847c9bfce7ec657952defbb4a311013e/lib/bugsnag/reporter.ex#L11-L32) and [`Bugsnag.Reporter.sync_report/2`](https://github.com/bugsnag-elixir/bugsnag-elixir/blob/577107f1847c9bfce7ec657952defbb4a311013e/lib/bugsnag/reporter.ex#L34-L56) to specify the type of the error being reported instead of determining the error class using the module of the exception struct.
The default behavior is still the same, if the option is not passed the error class will be the module of the given exception struct (i.e.
`exception.__struct__`).
> Add option to set error class instead of infering from the exception

- test/bugsnag/payload_sanitizer_test.exs
- test/bugsnag/payload_test.exs
Since Bugsnag supports Elixir 1.8 and above, it's time to replace the deprecated System.stacktrace/1 since Elixir 1.11 with pseudo-variable __STACKTRACE__.
> Remove deprecated system stacktrace warnings in tests
